spring.application.name=mercado

# Configuracao do Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracao do datasource (H2 em memoria)
spring.datasource.url=jdbc:h2:mem:cinema;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2
spring.datasource.initialization-mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Configuracao JPA (opcional, mas recomendado para melhor controle)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
cache.ttl=3600

api.security.token.secret=um_valor_secreto_bem_longo_e_seguro_para_jwt

logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG
